(source gnu)
(source melpa)

(depends-on "init-loader")
(depends-on "use-package")
(depends-on "sequential-command")
(depends-on "smartparens")

(depends-on "smart-compile")
(depends-on "autoinsert")
(depends-on "eldoc-extension")
(depends-on "fold-dwim")

(depends-on "google-c-style")
(depends-on "py-autopep8")
(depends-on "visual-regexp-steroids")

(depends-on "company")
(depends-on "irony")
(depends-on "company-irony")
(depends-on "company-irony-c-headers")
(depends-on "irony-eldoc")

(depends-on "flycheck")
(depends-on "flycheck-cask") 
(depends-on "flycheck-irony")
(depends-on "flycheck-pos-tip")

(depends-on "yasnippet")
(depends-on "color-theme-solarized")

(depends-on "undo-tree")
(depends-on "magit")
(depends-on "expand-region")

(depends-on "highlight-symbol")
(depends-on "ido-vertical-mode")
