#! /usr/bin/env bash

red=31
green=32
lyellow=33n
blue=34

ColorEcho() {
    local color=$1
    shift
    echo -e "\033[${color}m$@\033[m"
}

cd `dirname $0`
CURDIR=`pwd`
source "./shell/init.sh"

Install() {
    case ${OSTYPE} in
        darwin*)
	        LN='gln'
            ;;
        linux*)
	        LN='ln'
            ;;
    esac
    case ${1} in
	    all)
	        Install bash zsh tmux emacs vim dotfiles
	        return 0
	        ;;
	    default)
	        Install zsh tmux emacs dotfiles
	        return 0
	        ;;
	    bash)
	        ColorEcho $green "<--- installing bash settings --->"
            touch $HOME/.bash_profile
            echo "source $CURDIR/shell/init.sh" >> $HOME/.bash_profile
	        ;;
	    zsh)
	        # need zsh version ^5.3.1 (for auto complete)
	        # checked on mac, linux
	        ColorEcho $green "<--- installing zsh settings --->"
            zsh ./shell/install_zsh.sh
	        ;;
	    tmux)
	        ColorEcho $green "<--- installing tmux settings --->"
            git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
	        $LN --backup=numbered -s $CURDIR/tmux/tmux.conf ~/.tmux.conf
	        ;;
	    emacs)
            # checked on mac, linux
            # on linux : simple install, on mac : full install
	        ColorEcho $green "<--- installing emacs settings --->"
            ./emacs/install.sh
	        ;;
	    dotfiles)
	        ColorEcho $green "<--- installing many dotfiles --->"
	        for f in $CURDIR/dotfiles/* ; do
		        echo "create symlink ~/.`basename $f`"
		        $LN --backup=numbered -s  $f ~/.`basename $f`
	        done
            mkdir -p $HOME/.config
            for f in $CURDIR/config/*; do
                echo "create symlink ~/.config/`basename $f`"
                $LN --backup=numbered -s $f ~/.config/`basename $f`
            done
	        ;;
	    *)
	        return 0
	        ;;
    esac
    shift
    Install $@
}

ColorEcho $green "vvvvvv Install Start vvvvvv"

Install $@

ColorEcho $green "^^^^^^ Install End   ^^^^^^"
