version: 2
jobs:
    build:
        docker:
            - image: centos:7
        working_directory: ~/SettingFiles
        steps:
            - checkout
            - run: itamae/mitamae.sh
            - run: ~/tmp/mitamae-x86_64-linux local itamae/local.rb --log-level=debug
