 # tool
readonly RED=31
readonly GREEN=32
readonly YELLOW=33
readonly BLUE=34

function colored-echo {
    color=$1
    shift
    echo -e "\033[${color}m$@\033[m"
}

#Common Setting Files

if [ -d "${HOME}/.bash.d" ];then
    for f in "${HOME}"/.bash.d/*.sh;do
	source "$f" && colored-echo $GREEN "loaded : $f"
    done
else
    colored-echo $YELLOW "not found directory : .bash.d"
fi

#Local Setting Files

if [ -e "${HOME}/.bash_local" ];then
    source "${HOME}/.bash_local" && colored-echo $GREEN "loaded : $f"
else
    colored-echo $YELLOW "not found : .bash_local"
fi

export EDITOR=emacs

nvm-init

colored-echo $GREEN 'loaded : .bashrc'

export PATH="$PATH:"/Applications/microchip/xc16/v1.26/bin""

export PATH="$PATH:/Applications/microchip/xc8/v1.37/bin"
