if [ -f ~/.bashrc ]; then
    source ~/.bashrc
fi

export PATH="/usr/local/sbin:$PATH"

export PATH="$PATH:"/Applications/microchip/xc16/v1.26/bin""

export PATH="$PATH:/Applications/microchip/xc8/v1.37/bin"
